# Generated by Django 4.1.7 on 2023-04-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女")], verbose_name="性别"
            ),
        ),
    ]
