# Generated by Django 4.1.7 on 2023-05-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum_alter_userinfo_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "1级"), (2, "2级"), (3, "3级"), (4, "4级")],
                default=1,
                verbose_name="级别",
            ),
        ),
    ]
